### ISSUE TITLE
使用时候样式问题报错

### ISSUE THREAD

**Issue by linsaw** [ruoduan-hub/miniprogram-wecalendar#1]
![WX20230711-112505@2x](https://github.com/ruoduan-hub/miniprogram-wecalendar/assets/8231996/9dca47d7-7626-46a8-b1fa-afcf3324d039)
![1111](https://github.com/ruoduan-hub/miniprogram-wecalendar/assets/8231996/6f356785-0e86-4be0-81e7-7ebf26fc1835)

**Comment by ruoduan-hub** [comment]
> ![WX20230711-112505@2x](https://user-images.githubusercontent.com/8231996/252542520-9dca47d7-7626-46a8-b1fa-afcf3324d039.png) ![1111](https://user-images.githubusercontent.com/8231996/252542607-6f356785-0e86-4be0-81e7-7ebf26fc1835.png)

- 开启小程序开发工具的 less 选项, 然后重新构建npm包
```js
"useCompilerPlugins": [
            "less"
        ],
```
