### ISSUE TITLE
设置了markCalendarList

### ISSUE THREAD

**Issue by guozijian111** [ruoduan-hub/miniprogram-wecalendar#2]
markCalendarList不能异步

**Comment by ruoduan-hub** [comment]
> markCalendarList不能异步

Code example Please ！

**Comment by guozijian111** [comment]
![image](https://github.com/ruoduan-hub/miniprogram-wecalendar/assets/117898432/6b65a18f-dc4c-43c1-9932-bb756e9b33e6)

**Comment by ruoduan-hub** [comment]
> ![image](https://private-user-images.githubusercontent.com/117898432/328746198-6b65a18f-dc4c-43c1-9932-bb756e9b33e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjI0OTMsIm5iZiI6MTcxNTMyMjE5MywicGF0aCI6Ii8xMTc4OTg0MzIvMzI4NzQ2MTk4LTZiNjVhMThmLWRjNGMtNDNjMS05OTMyLWJiNzU2ZTliMzNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjIzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTJhYzc4ODQwN2QyNzNiOGM0ZGEwZjYxM2FkZWI1ZWRhYTQ4NmNjNjE0YjIxMWFmNTEyMzU5ZmU2OTc2MGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9hAUnB2txzziHQNgLk0JqgZxZCXwsFf7bUueLycGO2k)

> 根据性能要求, 在第一次渲染后 markCalendarList 就不会再次渲染，应当等标记数据获取到后再渲染组件 👇
使用 `wx:if="markCalendarList.length"`
```
<WeCalendar wx:if="markCalendarList.length" weeekLayer="2" showFolding="{{true}}" markCalendarList="{{markCalendarList}}" isToday="{{true}}" bind:onRangeDate="onRangeDate" bind:onSelect="onSelect" />

```

**Comment by ruoduan-hub** [comment]
+ miniprogram-wecalendar@1.3.0

Supported
